"""initial schema baseline

Revision ID: d60b8c63a676
Revises: 
Create Date: 2026-05-29 14:03:54.233327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60b8c63a676'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fetch_interval', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_settings',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('video_template', sa.String(length=50), nullable=False),
    sa.Column('image_prompt_language', sa.String(length=10), nullable=False),
    sa.Column('output_format', sa.String(length=10), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('image_quality', sa.String(length=20), nullable=False),
    sa.Column('image_style', sa.String(length=20), nullable=False),
    sa.Column('image_negative_prompt', sa.Text(), nullable=True),
    sa.Column('subtitle_enabled', sa.Boolean(), nullable=False),
    sa.Column('subtitle_font_size', sa.Integer(), nullable=False),
    sa.Column('subtitle_font_color', sa.String(length=20), nullable=False),
    sa.Column('subtitle_outline_width', sa.Integer(), nullable=False),
    sa.Column('subtitle_position', sa.String(length=10), nullable=False),
    sa.Column('subtitle_margin_bottom', sa.Integer(), nullable=False),
    sa.Column('portrait_composite_enabled', sa.Boolean(), nullable=False),
    sa.Column('portrait_bg_color', sa.String(length=20), nullable=False),
    sa.Column('portrait_title_text', sa.String(length=255), nullable=True),
    sa.Column('portrait_title_font_size', sa.Integer(), nullable=False),
    sa.Column('portrait_title_y', sa.Integer(), nullable=False),
    sa.Column('portrait_video_y', sa.Integer(), nullable=False),
    sa.Column('portrait_subtitle_font_size', sa.Integer(), nullable=False),
    sa.Column('portrait_subtitle_margin_v', sa.Integer(), nullable=False),
    sa.Column('portrait_title_color', sa.String(length=20), nullable=False),
    sa.Column('portrait_title_outline_color', sa.String(length=20), nullable=False),
    sa.Column('portrait_title_outline_width', sa.Integer(), nullable=False),
    sa.Column('portrait_title_shadow_enabled', sa.Boolean(), nullable=False),
    sa.Column('portrait_title_shadow_color', sa.String(length=20), nullable=False),
    sa.Column('portrait_title_shadow_opacity', sa.Float(), nullable=False),
    sa.Column('portrait_title_shadow_x', sa.Integer(), nullable=False),
    sa.Column('portrait_title_shadow_y', sa.Integer(), nullable=False),
    sa.Column('portrait_sub_title_text', sa.String(length=255), nullable=True),
    sa.Column('portrait_sub_title_font_size', sa.Integer(), nullable=False),
    sa.Column('portrait_sub_title_color', sa.String(length=20), nullable=False),
    sa.Column('portrait_sub_title_y', sa.Integer(), nullable=False),
    sa.Column('portrait_title_bg_enabled', sa.Boolean(), nullable=False),
    sa.Column('portrait_title_bg_color', sa.String(length=20), nullable=False),
    sa.Column('portrait_title_bg_opacity', sa.Float(), nullable=False),
    sa.Column('portrait_title_bg_padding', sa.Integer(), nullable=False),
    sa.Column('portrait_title_bg_shape', sa.String(length=20), nullable=False),
    sa.Column('portrait_title_bg_radius', sa.Integer(), nullable=False),
    sa.Column('portrait_title_bg_skew', sa.Integer(), nullable=False),
    sa.Column('tts_voice_id', sa.String(length=100), nullable=True),
    sa.Column('tts_voice_clone_id', sa.String(length=36), nullable=True),
    sa.Column('cover_prompt', sa.Text(), nullable=True),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('outro_text', sa.Text(), nullable=True),
    sa.Column('reference_content', sa.Text(), nullable=True),
    sa.Column('use_reference_content', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_template_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('extra_config', sa.Text(), nullable=True),
    sa.Column('change_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('extra_config', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_name')
    )
    op.create_table('provider_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('provider_key', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_base_url', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type', 'provider_key', 'model_id', name='uq_provider')
    )
    op.create_table('voice_clones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_key', sa.String(length=50), nullable=False),
    sa.Column('speaker_id', sa.String(length=100), nullable=False),
    sa.Column('reference_audio_path', sa.Text(), nullable=False),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('training_status', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('fetched_topics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=30), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'step_name', name='uq_pipeline_step')
    )
    op.create_table('publish_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('cover_width', sa.Integer(), nullable=True),
    sa.Column('cover_height', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cover_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'platform', name='uq_publish_asset_platform')
    )
    op.create_table('scripts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('video_outputs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('template_used', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('has_subtitles', sa.Boolean(), nullable=False),
    sa.Column('subtitle_file', sa.Text(), nullable=True),
    sa.Column('video_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('duration_hint', sa.Float(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('audio_file', sa.Text(), nullable=True),
    sa.Column('chapter_title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'segment_order', name='uq_segment_order')
    )
    op.create_table('image_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_configs.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_assets')
    op.drop_table('segments')
    op.drop_table('video_outputs')
    op.drop_table('scripts')
    op.drop_table('publish_assets')
    op.drop_table('pipeline_steps')
    op.drop_table('fetched_topics')
    op.drop_table('audio_assets')
    op.drop_table('articles')
    op.drop_table('voice_clones')
    op.drop_table('provider_configs')
    op.drop_table('prompt_templates')
    op.drop_table('prompt_template_history')
    op.drop_table('projects')
    op.drop_table('global_settings')
    op.drop_table('content_sources')
    # ### end Alembic commands ###
